# Generated by Django 5.2.1 on 2025-06-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_lesson_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standard',
            new_name='a_standard',
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='b_subject',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='c_section',
        ),
        migrations.RenameModel(
            old_name='Lesson',
            new_name='d_lesson',
        ),
        migrations.RenameModel(
            old_name='Subsection',
            new_name='e_subsection',
        ),
        migrations.RenameModel(
            old_name='Quiz',
            new_name='f_quiz',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='g_note',
        ),
    ]
