# Generated by Django 5.2.1 on 2025-06-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_standard_a_standard_rename_subject_b_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_standard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='b_subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='c_section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='d_lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='e_subsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='f_quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='g_note',
            options={},
        ),
    ]
