# Generated by Django 5.2.1 on 2025-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_a_standard_options_alter_b_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_standard',
            options={'verbose_name': 'Standard', 'verbose_name_plural': 'Standards'},
        ),
        migrations.AlterModelOptions(
            name='b_subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='c_section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='d_lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='e_subsection',
            options={'verbose_name': 'Subsection', 'verbose_name_plural': 'Subsections'},
        ),
        migrations.AlterModelOptions(
            name='f_quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='g_note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='a_standard',
            name='name',
            field=models.CharField(choices=[('1st', '1st Standard'), ('2nd', '2nd Standard'), ('3rd', '3rd Standard'), ('4th', '4th Standard'), ('5th', '5th Standard'), ('6th', '6th Standard'), ('7th', '7th Standard'), ('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th Standard')], max_length=100),
        ),
    ]
